<?php
return array(
    'create'                        => array('System SKU', 'Date', 'Buyer', 'Merchant SKU', 'Product Name', 'Supplier SKU', 'Unit Cost (Foreign)', 'Qty', 'Retail Price', 'Description', 'Weight (g)', 'Brand Prefix', 'Tags', 'Options'),
    'download'                      => array('System SKU', 'Date', 'Buyer', 'Product Name', 'Supplier SKU', 'Unit Cost (Foreign)', 'Qty', 'Retail Price', 'Description', 'Weight (g)', 'Brand Prefix', 'Tags', 'Options'),
    'replenishment'                 => array('System SKU', 'Unit Cost', 'Quantity'),
    'members'                       => array('Name', 'Email', 'Gender', 'Birthday', 'Mobile', 'Channel Name', 'Store Credits', 'Created At', 'Updated At'),
    'newsletter'                    => array('Email', 'Channel', 'Subscribe on', 'Unsubscribed on'),
    'upload'                        => array('item_status', 'product', 'item_date', 'buyer', 'client_sku', 'product_name', 'sku_supplier_code', 'item_cost', 'item_quantity', 'unit_price', 'product_desc', 'sku_weight', 'product_brand', 'category_id', 'sku_tag', 'option_name', 'option_value'),
    'transactions'                  => array('Order No.', '3rd Party Order Code', 'Customer Name', 'Ordered On', 'Grand Total', 'No. of Items', 'Status', 'Pay With'),
    'map'                           => array(
                                        'client_sku'        =>'Merchant SKU',
                                        'product_brand'     =>'Brand Prefix',
                                        'item_cost'         =>'Unit Cost (Foreign',
                                        'item_quantity'     =>'Qty',
                                        'sku_weight'        =>'Weight (g)',
                                        'item_retail_price' =>'Retail Price',
                                        'sku_tag'           =>'Tags',
                                        'option_name'       =>'Option Name',
                                        'option_value'      =>'Option Value'
                                    ),
    'sku'                           => array('Hubwire SKU', 'Supplier SKU', 'Product Name', 'Quantity', 'Cost Price', 'Retail Price', 'Options'),
    'consignmentReport'             => array('No.', 'SKU', 'Product Name', 'Options', 'Sale ID', 'No. Sent Originally', 'No. Items Sold', 'RRP'),
    'thirdParyCategories'           => array('Hubwire Product id', 'Product Name', 'product_id', 'category_code'),
    'thirdParyCategoriesList'       => array('category', 'category_code'),
    'outdatedCategoriesProducts'    => array('merchant_id', 'merchant_name', 'product_id', 'product_name', 'Hubwire SKU', 'category_id', 'category_name'),
    'return-transactions'           => array('Order Date', 'Return Date', 'Channel Name', 'Hubwire SKU', 'Order #', 'Supplier SKU', 'Brand', 'Size', 'Colour', 'Return Quantity', 'Retail Price', 'Shipping Fee', 'Refunded Amount'),
    'tp_report_headers_map'         => array(
                                        'Channel Type'          => 'channel_type',
                                        'Order ID'              => 'tp_order_code',
                                        'Item Ref ID'           => 'tp_item_id',
                                        'Hubwire SKU'           => 'hubwire_sku',
                                        'Product ID'            => 'product_id',
                                        'Quantity'              => 'quantity',
                                        'Item Status'           => 'item_status',
                                        'RRP'                   => 'unit_price',
                                        'Listing Price'         => 'sale_price',
                                        'Customer Paid Price'   => 'sold_price',
                                        'Channel Fees'          => 'channel_fees',
                                        'Shipping Fees'         => 'channel_shipping_fees',
                                        'Payment Gateway Fees'  => 'channel_payment_gateway_fees',
                                        'Net Payout'            => 'net_payout',
                                        'Paid Status'           => 'paid_status',
                                    ),
    'tp_report_headers'             => array('Channel Type', 'Order ID', 'Item Ref ID', 'Hubwire SKU', 'Product ID', 'Quantity', 'Item Status', 'RRP', 'Listing Price', 'Customer Paid Price', 'Channel Fees','Shipping Fees', 'Payment Gateway Fees','Net Payout', 'Paid Status'),
);