<?php
return [
    'reject' => [
        'reasons' => [
            'Damaged',
            'Past Expiry',
            'Item no longer on sale',
            'Other: Please specify'
        ]
    ],
    'reject_sku' => [
        'reasons' => [
            'Stock out',
            'Quantity adjustment',
            'Product Defect'
        ]
    ],
    'gst_no_hw' => env('GST_NO_HW'),
    'gst_no_fabspy' => env('GST_NO_FABSPY'),
    'gst_no_fmhw' => env('GST_NO_FMHW'),

    'channel_type'=>array(
        0 => 'Warehouse',
        1 => 'Online Store',
        2 => 'Marketplace',
        3 => 'Offline Store',
        4 => 'Consignment Counter',
        5 => 'B2B',
        6 => 'Shopify',
        7 => 'Lelong',
        8 => 'Lazada',
        9 => 'Zalora',
        10 => '11Street',
        11 => 'Distribution Center',
        12 => 'Warehouse',
        13 => 'LazadaSC',
        14 => 'Storefront Vendor',
        15 => 'RubberNeck',
        16 => 'BearInBag',
        17 => 'AmaxMall',
        18 => 'Shopee',
        19 => 'Shopify POS',
    ),

    'channel_type_type' => array(
        'Sales'         => 'Sales',
        'Distribution'  => 'Distribution',
        // 'Deprecated'    => 'Deprecated',
    ),

    'sales'=>array(
        'search_status' => array(
            0 => 'Unknown',
            11 => 'Failed',
            12 => 'Pending',
            21 => 'New',
            22 => 'Picking',
            23 => 'Packing',
            24 => 'ReadyToShip',
            31 => 'Shipped',
            32 => 'Completed',
        ),
        'status' => array(
            'failed' => array(
                'Failed' => 'Failed',
                'Pending' => 'Pending'
            ),
            'pending' => array(
                'Pending' => 'Pending',
                'Paid' => 'Paid'
            ),
            'paid' => array(
                'Paid' => 'Paid',
                'Picking' => 'Picking',
                'Packing' => 'Packing',
                'Shipped' => 'Shipped',
                'Completed' => 'Completed',
                'Cancelled' => 'Cancelled'
            ),
            '*' => array(
                'Picking' => 'Picking',
                'Packing' => 'Packing',
                'Shipped' => 'Shipped',
                'Completed' => 'Completed',
                'Cancelled' => 'Cancelled'
            ),
        ),
        'payment' => array(
            'iPay88' => 'iPay88',
            'Paypal' => 'Paypal',
            'Store Credits' => 'Store Credits',
            'Promo Code' => 'Promo Code',
            'Ezypay' => 'Ezypay',
            'Netpay' => 'Netpay',
            'Cash' => 'Cash',
            'External-Credit' => 'External Credit',
            'External-Debit' => 'External Debit',
            'Universal' => 'Universal',
            'Cybersource' => 'Cybersource',
            'Cybersource_Ca' => 'Cybersource',
            'CashOnDelivery' => 'CashOnDelivery',
            'eghl_payment_gateway' => 'Eghl Payment Gateway',
            'Gift_card' => 'Gift Card',
            'Free' => 'Free',
            'Bogus' => 'Test',
            'NoPayment' => 'No Payment',
        ),
    ),

    'stock_transfer' => array (
        'do_type' => array('Procurement Batch', 'Normal','Stock Out'),
        'statuses' => array('Draft', 'In Transit', 'Received'),
    ),

    'date_format'   => 'd-m-Y',
    'date_format_invoice'  => 'd F Y',
    'date_format_invoice_no' => array(
            'Ym'    =>'Ym (e.g. 201612)' ,
            'ym'    =>'ym (e.g. 1612)' ,
            'ymd'   =>'ymd (e.g. 1612)' ,
            'Ymd'   =>'Ymd (e.g. 20161231)' ,
            'my'    =>'my (e.g. 1216)' ,
            'mY'    =>'mY (e.g. 122016)' ,
            'dmy'   =>'dmy (e.g. 311216)' ,
            'dmY'   =>'dmY (e.g. 31122016)'
        ), //According to date format
    'date_format_drp'   => 'DD-MM-YYYY',
    'date_format_dp'   => 'dd-mm-yyyy',
    'datetime_format'   => 'd-m-Y h:i A',

    'currency_list' => array(
        'ALL' => 'Albania Lek',
        'AFN' => 'Afghanistan Afghani',
        'ARS' => 'Argentina Peso',
        'AWG' => 'Aruba Guilder',
        'AUD' => 'Australia Dollar',
        'AZN' => 'Azerbaijan New Manat',
        'BSD' => 'Bahamas Dollar',
        'BBD' => 'Barbados Dollar',
        'BDT' => 'Bangladeshi taka',
        'BYR' => 'Belarus Ruble',
        'BZD' => 'Belize Dollar',
        'BMD' => 'Bermuda Dollar',
        'BOB' => 'Bolivia Boliviano',
        'BAM' => 'Bosnia and Herzegovina Convertible Marka',
        'BWP' => 'Botswana Pula',
        'BGN' => 'Bulgaria Lev',
        'BRL' => 'Brazil Real',
        'BND' => 'Brunei Darussalam Dollar',
        'KHR' => 'Cambodia Riel',
        'CAD' => 'Canada Dollar',
        'KYD' => 'Cayman Islands Dollar',
        'CLP' => 'Chile Peso',
        'CNY' => 'China Yuan Renminbi',
        'COP' => 'Colombia Peso',
        'CRC' => 'Costa Rica Colon',
        'HRK' => 'Croatia Kuna',
        'CUP' => 'Cuba Peso',
        'CZK' => 'Czech Republic Koruna',
        'DKK' => 'Denmark Krone',
        'DOP' => 'Dominican Republic Peso',
        'XCD' => 'East Caribbean Dollar',
        'EGP' => 'Egypt Pound',
        'SVC' => 'El Salvador Colon',
        'EEK' => 'Estonia Kroon',
        'EUR' => 'Euro Member Countries',
        'FKP' => 'Falkland Islands (Malvinas) Pound',
        'FJD' => 'Fiji Dollar',
        'GHC' => 'Ghana Cedis',
        'GIP' => 'Gibraltar Pound',
        'GTQ' => 'Guatemala Quetzal',
        'GGP' => 'Guernsey Pound',
        'GYD' => 'Guyana Dollar',
        'HNL' => 'Honduras Lempira',
        'HKD' => 'Hong Kong Dollar',
        'HUF' => 'Hungary Forint',
        'ISK' => 'Iceland Krona',
        'INR' => 'India Rupee',
        'IDR' => 'Indonesia Rupiah',
        'IRR' => 'Iran Rial',
        'IMP' => 'Isle of Man Pound',
        'ILS' => 'Israel Shekel',
        'JMD' => 'Jamaica Dollar',
        'JPY' => 'Japan Yen',
        'JEP' => 'Jersey Pound',
        'KZT' => 'Kazakhstan Tenge',
        'KPW' => 'Korea (North) Won',
        'KRW' => 'Korea (South) Won',
        'KGS' => 'Kyrgyzstan Som',
        'LAK' => 'Laos Kip',
        'LVL' => 'Latvia Lat',
        'LBP' => 'Lebanon Pound',
        'LRD' => 'Liberia Dollar',
        'LTL' => 'Lithuania Litas',
        'MKD' => 'Macedonia Denar',
        'MYR' => 'Malaysia Ringgit',
        'MUR' => 'Mauritius Rupee',
        'MXN' => 'Mexico Peso',
        'MNT' => 'Mongolia Tughrik',
        'MZN' => 'Mozambique Metical',
        'NAD' => 'Namibia Dollar',
        'NPR' => 'Nepal Rupee',
        'ANG' => 'Netherlands Antilles Guilder',
        'NZD' => 'New Zealand Dollar',
        'NIO' => 'Nicaragua Cordoba',
        'NGN' => 'Nigeria Naira',
        'NOK' => 'Norway Krone',
        'OMR' => 'Oman Rial',
        'PKR' => 'Pakistan Rupee',
        'PAB' => 'Panama Balboa',
        'PYG' => 'Paraguay Guarani',
        'PEN' => 'Peru Nuevo Sol',
        'PHP' => 'Philippines Peso',
        'PLN' => 'Poland Zloty',
        'QAR' => 'Qatar Riyal',
        'RON' => 'Romania New Leu',
        'RUB' => 'Russia Ruble',
        'SHP' => 'Saint Helena Pound',
        'SAR' => 'Saudi Arabia Riyal',
        'RSD' => 'Serbia Dinar',
        'SCR' => 'Seychelles Rupee',
        'SGD' => 'Singapore Dollar',
        'SBD' => 'Solomon Islands Dollar',
        'SOS' => 'Somalia Shilling',
        'ZAR' => 'South Africa Rand',
        'LKR' => 'Sri Lanka Rupee',
        'SEK' => 'Sweden Krona',
        'CHF' => 'Switzerland Franc',
        'SRD' => 'Suriname Dollar',
        'SYP' => 'Syria Pound',
        'TWD' => 'Taiwan New Dollar',
        'THB' => 'Thailand Baht',
        'TTD' => 'Trinidad and Tobago Dollar',
        'TRY' => 'Turkey Lira',
        'TRL' => 'Turkey Lira',
        'TVD' => 'Tuvalu Dollar',
        'UAH' => 'Ukraine Hryvna',
        'GBP' => 'United Kingdom Pound',
        'USD' => 'United States Dollar',
        'UYU' => 'Uruguay Peso',
        'UZS' => 'Uzbekistan Som',
        'VEF' => 'Venezuela Bolivar',
        'VND' => 'Vietnam Dong',
        'YER' => 'Yemen Rial',
        'ZWD' => 'Zimbabwe Dollar'
    ),

    'product_management_status' =>  array(
        0   =>  'Pending',
        1   =>  'Received',
    ),

    'third_party_categories_applicable' => array(
        7   => 'Lelong',
        8   => 'Lazada',
        9   => 'Zalora',
        10  => '11Street',
        13  => 'LazadaSC',
        15  => 'RubberNeck',
        16  => 'BearInBag',
        17  => 'AmaxMall',
    ),

    'order_notes_type' => array(
        'General' => 'General',
        'Attention Required' => 'Attention Required',
    ),

    'order_history_event_type_class' => array(
        'Status Updated'                    =>  'bg-blue fa-asterisk',
        'Order Created'                     =>  'bg-green fa-shopping-cart',
        'Order Paid'                        =>  'bg-green fa-dollar',
        'Order Completed'                   =>  'bg-green fa-check',
        'Order Cancelled'                   =>  'bg-red fa-remove',
        'Item Returned'                     =>  'bg-yellow fa-truck',
        'Item Status Updated'               =>  'bg-blue fa-info',
        'Consignment Number Updated'        =>  'bg-blue fa-tag',
        'Consignment Number Sent/Requested' =>  'bg-blue fa-info',
        'Consignment Number Update Failed'  =>  'bg-red fa-exclamation',
        'Returned Item: Restocked'          =>  'bg-blue fa-info',
        'Returned Item: Rejected'           =>  'bg-blue fa-info',
        'Returned Item: In Transit'         =>  'bg-blue fa-truck',
        'Added General Note'                =>  'bg-blue fa-sticky-note-o',
        'Added Attention Required Note'     =>  'bg-red fa-exclamation',
        'Commented on Note'                 =>  'bg-blue fa-commenting-o',
        'Attention Required Note Resolved'  =>  'bg-green fa-thumbs-o-up',
    ),

    'dashboard_color_codes' => array(
        '#3c8dbc',
        '#dd4b39',
        '#00a65a',
        '#00c0ef',
        '#f39c12',
        '#0073b7',
        '#7094db',
        '#001F3F',
        '#39CCCC',
        '#3D9970',
        '#01FF70',
        '#FF851B',
        '#F012BE',
        '#605ca8',
        '#D81B60',
        '#111',
        '#d2d6de',
        '#333',
    ),

    // documents to print for bulk print feature in picking manifest
    'docs_to_print' => array(
        0   => 'Order Sheet',
        1   => 'Hubwire Tax Invoice',
        2   => 'Return Slip',
        3   => 'Zalora Tax Invoice',
    ),

    'shipping_provider' => array(
        "GDex",
        "Pos Laju",
        "Skynet",
    ),

    'generate_report_type' => array(
        'sales' => 'Sales Report',
        'merchant' => 'Merchant Performance Report',
    ),

    'bank_list' => array(
        'Affin Bank Berhad' => 'Affin Bank Berhad',
        'Alliance Bank Malaysia Berhad' => 'Alliance Bank Malaysia Berhad',
        'AmBank (M) Berhad' => 'AmBank (M) Berhad',
        'CIMB Bank Berhad' => 'CIMB Bank Berhad',
        'Citibank Berhad' => 'Citibank Berhad',
        'HSBC Bank Malaysia Berhad' => 'HSBC Bank Malaysia Berhad',
        'Hong Leong Bank Berhad' => 'Hong Leong Bank Berhad',
        'Malayan Banking Berhad' => 'Malayan Banking Berhad',
        'OCBC Bank (Malaysia) Berhad' => 'OCBC Bank (Malaysia) Berhad',
        'Public Bank Berhad' => 'Public Bank Berhad',
        'RHB Bank Berhad' => 'RHB Bank Berhad',
        'Standard Chartered Bank Malaysia Berhad' => 'Standard Chartered Bank Malaysia Berhad',
        'United Overseas Bank (Malaysia) Bhd' => 'United Overseas Bank (Malaysia) Bhd',
    ),

    'payment_methods' => array(
        'Telegraphic Transfer' => 'Telegraphic Transfer',
        'Cheque' => 'Cheque',
        'Online Transfer' => 'Online Transfer',
        'Bank Deposit' => 'Bank Deposit',
        'Credit/Debit Card' => 'Credit/Debit Card',
    ),

    'tp_reports_export_options' => array(
        "Selected",
        "All",
        "Verified",
        "Unverified",
        "Not Found",
        "Tax Invoice Data"
    ),

    'tp_reports_item_status' => array(
        "Unverified" => "Unverified",
        "Verified" => "Verified",
        "Completed" => "Completed",
        "Not Found" => "Not Found",
    ),

    'tax_invoice_file_name' => array(
        0 => "pending_third_party_payment",
        1 => "pending_payment_by_marketplace",
        2 => "paid_by_marketplace",
        3 => "completed",
    ),

    'return_reason' => array(
        'Wrongly sent by FMHW'                      =>  'Wrongly sent by FMHW',
        'Marketplace return within return policy'   =>  'Marketplace return within return policy',
        'Undelivered'                               =>  'Undelivered',
        'COD - unpaid'                              =>  'COD - unpaid',
        'Emergency recall'                          =>  'Emergency recall',
    ),
    
    'contract_type' => array(
        'Channel Fee'   =>  'Channel Fee',
        'Hubwire Fee'   =>  'Hubwire Fee'
    ),

    'malaysia_region' => array(
        'East Malaysia'     =>  'East Malaysia',
        'West Malaysia'     =>  'West Malaysia',
    ),

    'malaysia_state' => array(
        'Perlis'            =>  'Perlis',
        'Kedah'             =>  'Kedah',
        'Kelantan'          =>  'Kelantan',
        'Terengganu'        =>  'Terengganu',
        'Pahang'            =>  'Pahang',
        'Penang'            =>  'Penang',
        'Perak'             =>  'Perak',
        'Selangor'          =>  'Selangor',
        'Malacca'           =>  'Malacca',
        'Negeri Sembilan'   =>  'Negeri Sembilan',
        'Johor'             =>  'Johor',
        'Sabah'             =>  'Sabah',
        'Sarawak'           =>  'Sarawak',
        'Kuala Lumpur'      =>  'Kuala Lumpur',
        'Labuan'            =>  'Labuan',
    ),
    'third_party_report_remarks' => array(
        'Third Party Order' => 'Third Party Order',
        'Third Party Item' => 'Third Party Item',
        'Hubwire SKU' => 'Hubwire SKU',
        'Product ID' => 'Product ID',
        'RRP' => 'RRP',
        'Listing Price' => 'Listing Price',
        'Net Payout' => 'Net Payout',
        'Item Status' => 'Item Status'
    ),
    'countryList' => array(
        'AF' => 'Afghanistan',
        'AX' => 'Åland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua & Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AC' => 'Ascension Island',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia & Herzegovina',
        'BW' => 'Botswana',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'VG' => 'British Virgin Islands',
        'BN' => 'Brunei',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'IC' => 'Canary Islands',
        'CV' => 'Cape Verde',
        'BQ' => 'Caribbean Netherlands',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'EA' => 'Ceuta & Melilla',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo - Brazzaville',
        'CD' => 'Congo - Kinshasa',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Côte d’Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Curaçao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DG' => 'Diego Garcia',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong SAR China',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'XK' => 'Kosovo',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Laos',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macau SAR China',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar (Burma)',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'KP' => 'North Korea',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territories',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn Islands',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Réunion',
        'RO' => 'Romania',
        'RU' => 'Russia',
        'RW' => 'Rwanda',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'São Tomé & Príncipe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SX' => 'Sint Maarten',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia & South Sandwich Islands',
        'KR' => 'South Korea',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'BL' => 'St. Barthélemy',
        'SH' => 'St. Helena',
        'KN' => 'St. Kitts & Nevis',
        'LC' => 'St. Lucia',
        'MF' => 'St. Martin',
        'PM' => 'St. Pierre & Miquelon',
        'VC' => 'St. Vincent & Grenadines',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard & Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syria',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad & Tobago',
        'TA' => 'Tristan da Cunha',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks & Caicos Islands',
        'TV' => 'Tuvalu',
        'UM' => 'U.S. Outlying Islands',
        'VI' => 'U.S. Virgin Islands',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VA' => 'Vatican City',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'WF' => 'Wallis & Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ),
];
